var mongoose = require('mongoose');
var userSchema = mongoose.Schema({
    username:{type:String, required: true,unique:true},
    password:{type:String, required: true},
    name:{type:String, required:true},
    registerno:{type:String, required:true},
    dept:{type:String,required:true},
    yos:{type:String, required:true},
    ant1:{type:String, required:true},
    ant2:{type:String, required:true},
    ant3:{type:String, required:true},
    antu:{type:String, required:true},
    antas:{type:String, required:true},
    antm:{type:String, required:true},
    mp1:{type:String, required:true},
    mp2:{type:String, required:true},
    mp3:{type:String, required:true},
    mpu:{type:String, required:true},
    mpas:{type:String, required:true},
    mpm:{type:String, required:true},
    cn1:{type:String, required:true},
    cn2:{type:String, required:true},
    cn3:{type:String, required:true},
    cnu:{type:String, required:true},
    cnas:{type:String, required:true},
    cnm:{type:String, required:true},
    toc1:{type:String, required:true},
    toc3:{type:String, required:true},
    toc3:{type:String, required:true},
    tocu:{type:String, required:true},
    tocas:{type:String, required:true},
    tocm:{type:String, required:true},
    ood1:{type:String, required:true},
    ood3:{type:String, required:true},
    ood3:{type:String, required:true},
    oodu:{type:String, required:true},
    oodas:{type:String, required:true},
    oodm:{type:String, required:true},
    gis1:{type:String, required:true},
    gis3:{type:String, required:true},
    gis3:{type:String, required:true},
    gisu:{type:String, required:true},
    gisas:{type:String, required:true},
    gism:{type:String, required:true},
})
module.exports = mongoose.model('User', userSchema);